//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupportToolGUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITSupportToolGUI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Printer.
        /// </summary>
        internal static string AddPrinterLabel {
            get {
                return ResourceManager.GetString("AddPrinterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and add network printers..
        /// </summary>
        internal static string AddPrinterToolTip {
            get {
                return ResourceManager.GetString("AddPrinterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selected.
        /// </summary>
        internal static string AddSelectedButtonText {
            get {
                return ResourceManager.GetString("AddSelectedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Information.
        /// </summary>
        internal static string ComputerInformationTitle {
            get {
                return ResourceManager.GetString("ComputerInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name:.
        /// </summary>
        internal static string ComputerNameLabel {
            get {
                return ResourceManager.GetString("ComputerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected via Ethernet.
        /// </summary>
        internal static string ConnectedViaEthernet {
            get {
                return ResourceManager.GetString("ConnectedViaEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all info to the clipboard..
        /// </summary>
        internal static string CopyInfoTip {
            get {
                return ResourceManager.GetString("CopyInfoTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Fix.
        /// </summary>
        internal static string ExecuteScriptButtonText {
            get {
                return ResourceManager.GetString("ExecuteScriptButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FortiClient Connected.
        /// </summary>
        internal static string FortiClientConnected {
            get {
                return ResourceManager.GetString("FortiClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FortiClient Disconnected.
        /// </summary>
        internal static string FortiClientDisconnected {
            get {
                return ResourceManager.GetString("FortiClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your STARK username and password..
        /// </summary>
        internal static string InstructionsBullet2 {
            get {
                return ResourceManager.GetString("InstructionsBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK..
        /// </summary>
        internal static string InstructionsBullet3 {
            get {
                return ResourceManager.GetString("InstructionsBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password: Windows password (not pincode).
        /// </summary>
        internal static string InstructionsExamplePassword {
            get {
                return ResourceManager.GetString("InstructionsExamplePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: Fx: D123ABC or Email.
        /// </summary>
        internal static string InstructionsExampleUsername {
            get {
                return ResourceManager.GetString("InstructionsExampleUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Click &quot;Run Fix&quot;.
        /// </summary>
        internal static string InstructionsStep1 {
            get {
                return ResourceManager.GetString("InstructionsStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will open the Wi-Fi list on the right side of your screen..
        /// </summary>
        internal static string InstructionsStep1Body {
            get {
                return ResourceManager.GetString("InstructionsStep1Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Reconnect to StarkGroup.
        /// </summary>
        internal static string InstructionsStep2 {
            get {
                return ResourceManager.GetString("InstructionsStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the list, find and click on StarkGroup. You will see this login window:.
        /// </summary>
        internal static string InstructionsStep2Body {
            get {
                return ResourceManager.GetString("InstructionsStep2Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Wi-Fi Connection.
        /// </summary>
        internal static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string IPAddressLabel {
            get {
                return ResourceManager.GetString("IPAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://starkworkspace.sharepoint.com/sites/toolboxstarkgroup/_layouts/15/news.aspx?title=Latest%20news&amp;newsSource=3&amp;instanceId=3c3acc5f-432c-4b7b-a6b3-0426a6dad5cf&amp;webPartId=8c88f208-6c77-4bdb-86a0-0c47b4316588&amp;serverRelativeUrl=%2Fsites%2Ftoolboxstarkgroup%2FSitePages%2FHome.aspx&amp;pagesListId=b5016441-c0e2-46b8-8e37-38673915ad42&amp;audienceTargetingEnabled=true.
        /// </summary>
        internal static string ITMessagesURL {
            get {
                return ResourceManager.GetString("ITMessagesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Restart:.
        /// </summary>
        internal static string LastRestartLabel {
            get {
                return ResourceManager.GetString("LastRestartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active connection.
        /// </summary>
        internal static string NoActiveConnection {
            get {
                return ResourceManager.GetString("NoActiveConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to WiFi.
        /// </summary>
        internal static string NotConnectedToWiFi {
            get {
                return ResourceManager.GetString("NotConnectedToWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Messages.
        /// </summary>
        internal static string OpenITMessagesLabel {
            get {
                return ResourceManager.GetString("OpenITMessagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the IT messages portal..
        /// </summary>
        internal static string OpenITMessagesTip {
            get {
                return ResourceManager.GetString("OpenITMessagesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string OpenPasswordResetLabel {
            get {
                return ResourceManager.GetString("OpenPasswordResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the portal to change your password..
        /// </summary>
        internal static string OpenPasswordResetTip {
            get {
                return ResourceManager.GetString("OpenPasswordResetTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Help.
        /// </summary>
        internal static string OpenRemoteHelpLabel {
            get {
                return ResourceManager.GetString("OpenRemoteHelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the Stark Remote Help application..
        /// </summary>
        internal static string OpenRemoteHelpTip {
            get {
                return ResourceManager.GetString("OpenRemoteHelpTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selfix.
        /// </summary>
        internal static string OpenTicketSystemLabel {
            get {
                return ResourceManager.GetString("OpenTicketSystemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the ticket system to report issues..
        /// </summary>
        internal static string OpenTicketSystemTip {
            get {
                return ResourceManager.GetString("OpenTicketSystemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Version:.
        /// </summary>
        internal static string OSVersionLabel {
            get {
                return ResourceManager.GetString("OSVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one printer to add..
        /// </summary>
        internal static string PrinterErrorNoPrinterSelected {
            get {
                return ResourceManager.GetString("PrinterErrorNoPrinterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Printer Selected.
        /// </summary>
        internal static string PrinterErrorNoPrinterSelectedTitle {
            get {
                return ResourceManager.GetString("PrinterErrorNoPrinterSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Name.
        /// </summary>
        internal static string PrinterNameHeader {
            get {
                return ResourceManager.GetString("PrinterNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Can only add Ricoh printers..
        /// </summary>
        internal static string PrinterNotice {
            get {
                return ResourceManager.GetString("PrinterNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer installation complete..
        /// </summary>
        internal static string PrinterReportComplete {
            get {
                return ResourceManager.GetString("PrinterReportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Add:.
        /// </summary>
        internal static string PrinterReportFailed {
            get {
                return ResourceManager.GetString("PrinterReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Added:.
        /// </summary>
        internal static string PrinterReportSuccess {
            get {
                return ResourceManager.GetString("PrinterReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Report.
        /// </summary>
        internal static string PrinterReportTitle {
            get {
                return ResourceManager.GetString("PrinterReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string PrinterSelectHeader {
            get {
                return ResourceManager.GetString("PrinterSelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a location number to find Ricoh printers..
        /// </summary>
        internal static string PrinterStatusEnterSiteId {
            get {
                return ResourceManager.GetString("PrinterStatusEnterSiteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation process finished..
        /// </summary>
        internal static string PrinterStatusFinished {
            get {
                return ResourceManager.GetString("PrinterStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} Ricoh printers..
        /// </summary>
        internal static string PrinterStatusFound {
            get {
                return ResourceManager.GetString("PrinterStatusFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing selected printers, please wait....
        /// </summary>
        internal static string PrinterStatusInstalling {
            get {
                return ResourceManager.GetString("PrinterStatusInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ricoh printers found for that store number..
        /// </summary>
        internal static string PrinterStatusNotFound {
            get {
                return ResourceManager.GetString("PrinterStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for printers....
        /// </summary>
        internal static string PrinterStatusSearching {
            get {
                return ResourceManager.GetString("PrinterStatusSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Printer.
        /// </summary>
        internal static string PrinterViewTitle {
            get {
                return ResourceManager.GetString("PrinterViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Wi-Fi.
        /// </summary>
        internal static string RunScriptLabel {
            get {
                return ResourceManager.GetString("RunScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show instructions on how to fix the Wi-Fi connection..
        /// </summary>
        internal static string RunScriptTip {
            get {
                return ResourceManager.GetString("RunScriptTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButtonText {
            get {
                return ResourceManager.GetString("SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Support Information.
        /// </summary>
        internal static string ServiceDeskCardTitle {
            get {
                return ResourceManager.GetString("ServiceDeskCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: itsupport@stark.dk.
        /// </summary>
        internal static string ServiceDeskEmail {
            get {
                return ResourceManager.GetString("ServiceDeskEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday – Friday: 06:00–17:00.
        /// </summary>
        internal static string ServiceDeskHours {
            get {
                return ResourceManager.GetString("ServiceDeskHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Support.
        /// </summary>
        internal static string ServiceDeskLabel {
            get {
                return ResourceManager.GetString("ServiceDeskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: 8252 6900.
        /// </summary>
        internal static string ServiceDeskPhone {
            get {
                return ResourceManager.GetString("ServiceDeskPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Support information.
        /// </summary>
        internal static string ServiceDeskTitle {
            get {
                return ResourceManager.GetString("ServiceDeskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the IT Support contact information..
        /// </summary>
        internal static string ServiceDeskToolTip {
            get {
                return ResourceManager.GetString("ServiceDeskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Information.
        /// </summary>
        internal static string ShowComputerInfoLabel {
            get {
                return ResourceManager.GetString("ShowComputerInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detailed information about your computer..
        /// </summary>
        internal static string ShowComputerInfoToolTip {
            get {
                return ResourceManager.GetString("ShowComputerInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store nr.:.
        /// </summary>
        internal static string SiteIdLabel {
            get {
                return ResourceManager.GetString("SiteIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network:.
        /// </summary>
        internal static string SSIDLabel {
            get {
                return ResourceManager.GetString("SSIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the interface language to your native language..
        /// </summary>
        internal static string SwitchToDanishTip {
            get {
                return ResourceManager.GetString("SwitchToDanishTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch the interface language to English..
        /// </summary>
        internal static string SwitchToEnglishTip {
            get {
                return ResourceManager.GetString("SwitchToEnglishTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN IP Address:.
        /// </summary>
        internal static string VPNIPAddressLabel {
            get {
                return ResourceManager.GetString("VPNIPAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Status:.
        /// </summary>
        internal static string VPNStatusLabel {
            get {
                return ResourceManager.GetString("VPNStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi for Mobile Phones.
        /// </summary>
        internal static string WifiCardTitle {
            get {
                return ResourceManager.GetString("WifiCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarkIOT.
        /// </summary>
        internal static string WifiEmployeeNetworkNameValue {
            get {
                return ResourceManager.GetString("WifiEmployeeNetworkNameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int3rnet4iPads.
        /// </summary>
        internal static string WifiEmployeeNetworkPasswordValue {
            get {
                return ResourceManager.GetString("WifiEmployeeNetworkPasswordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string WifiNetworkNameLabel {
            get {
                return ResourceManager.GetString("WifiNetworkNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        internal static string WifiNetworkPasswordLabel {
            get {
                return ResourceManager.GetString("WifiNetworkPasswordLabel", resourceCulture);
            }
        }
    }
}
